name: GH Pages Sphinx Docs
on: [push, pull_request]

# Required permissions for Pages (deploy-pages@v4 also needs actions: read)
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

# Only one concurrent deployment; don't cancel in-progress
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Upgrade pip & install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r docs/source/docs_requirements.txt
          pip install -e .

      - name: Sphinx build
        run: sphinx-build docs/source docs/build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/build

  deploy:
    if: startsWith(github.event.ref, 'refs/tags/v')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
