name: Build Wheels

on: [push, pull_request]

jobs:
  multi_platform_test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-14, ubuntu-latest]
        py: ["3.10", "3.11", "3.12"]

    name: Build & test on ${{ matrix.os }} / Python ${{ matrix.py }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
          cache: pip

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run unit tests
        run: pytest -q

  build_wheels:
    runs-on: ubuntu-latest
    name: Build sdist & wheel

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Upgrade pip and install build deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build

      - name: Build distributions
        run: python -m build

      - name: Test built wheel
        run: |
          pip install --no-index --find-links=./dist pyswmm
          pytest -q

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyswmm-dist
          path: dist/*
          if-no-files-found: error
          retention-days: 7